

REM permanently set some path variables
SETX OPENCV2_PATH D:\InstalledPrograms\opencv_2.4\build /m
SETX OPENCV2_INCLUDE %OPENCV2_PATH%\include /m
SETX OPENCV2_BIN_x86 %OPENCV2_PATH%\x86\vc12\bin /m
SETX OPENCV2_LIB_x86 %OPENCV2_PATH%\x86\vc12\lib /m
SETX OPENCV2_STATICLIB_x86 %OPENCV2_PATH%\x86\vc12\staticlib /m

ECHO %OPENCV2_PATH
ECHO %OPENCV2_INCLUDE%
ECHO %OPENCV2_BIN_x86%
ECHO %OPENCV2_LIB_x86%
ECHO %OPENCV2_STATICLIB_x86%